# Generated by Django 4.0.6 on 2023-05-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_centeral',
            field=models.BooleanField(default=False, verbose_name='For Centeral Billing (Web)'),
        ),
    ]
