# Generated by Django 4.0.6 on 2023-05-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_branch_is_centeral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='is_centeral',
            new_name='is_central',
        ),
    ]
