# Generated by Django 4.0.6 on 2023-05-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_current_fiscal_year_enddayrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='enddayrecord',
            name='date',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
