# Generated by Django 4.0.6 on 2023-05-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_enddaydailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='enddaydailyreport',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.branch'),
        ),
        migrations.AddField(
            model_name='enddaydailyreport',
            name='terminal',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
