# Generated by Django 4.0.6 on 2023-05-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_mailrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='enddaydailyreport',
            name='total_sale',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_central',
            field=models.BooleanField(default=False, verbose_name='For Central Billing (Web)'),
        ),
    ]
