# Generated by Django 4.0.6 on 2023-05-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_enddaydailyreport_total_sale_alter_branch_is_central'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mail_recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.mailrecipient')),
            ],
        ),
    ]
