# Generated by Django 4.0.6 on 2023-06-27 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_mailsendrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='enddaydailyreport',
            name='created_date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
