# Generated by Django 4.0.6 on 2023-06-28 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_mailsendrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enddaydailyreport',
            options={},
        ),
        migrations.AddField(
            model_name='enddaydailyreport',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='enddaydailyreport',
            unique_together={('created_date', 'branch')},
        ),
    ]
