# Generated by Django 4.0.6 on 2023-05-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemreconcilationapiitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='itemreconcilationapiitem',
            unique_together={('branch', 'product', 'date')},
        ),
    ]
