# Generated by Django 4.0.6 on 2023-05-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_itemreconcilationapiitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_billing_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_produced',
            field=models.BooleanField(default=False),
        ),
    ]
