# Generated by Django 4.0.6 on 2023-05-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_is_billing_item_alter_product_is_produced'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(default=0.0),
        ),
    ]
