# Generated by Django 4.0.6 on 2023-05-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_mailsendrecord'),
        ('product', '0005_product_cost_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemreconcilationapiitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemreconcilationapiitem',
            name='terminal',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='itemreconcilationapiitem',
            unique_together={('branch', 'product', 'date', 'terminal')},
        ),
    ]
