# Generated by Django 4.0.6 on 2023-05-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitemvoid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
