# Generated by Django 4.0.6 on 2023-05-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100, unique=True)),
                ('is_editable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_name', models.CharField(max_length=200, unique=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_editable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountSubLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_ledger_name', models.CharField(max_length=100)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_editable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CumulativeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_name', models.CharField(max_length=200)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('value_changed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('miti', models.CharField(max_length=15)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiscal_year', models.CharField(max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TblJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('journal_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiscal_year', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TblDrJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('particulars', models.TextField(max_length=255)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.tbljournalentry')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountledger')),
                ('sub_ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountsubledger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TblCrJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('particulars', models.TextField(max_length=255)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.tbljournalentry')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountledger')),
                ('sub_ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountsubledger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalYearSubLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_ledger_name', models.CharField(max_length=100)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_editable', models.BooleanField(default=True)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountledger')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYearLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_name', models.CharField(max_length=200)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_editable', models.BooleanField(default=True)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('account_chart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountchart')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('credit_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_ledger', to='accounting.accountledger')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='accounting.accountledger')),
                ('sub_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.accountsubledger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
